#dataset: "UniProtGOA_HUMAN"
deepgraphgo_data: '../DeepGraphGO/data'
uniprotgoa_path: '~/Bioinformatics_ExternalData/UniProtGOA/goa_uniprot_all.processed.parquet'
#root_path: "../Multiplex-Graph-Embedding/data/heteronetwork/HUMAN_gtex_uniprot_MirTarBase_LncBase_lncRNA2Target_STRING_mRNAprotein_network.pickle"
labels_dataset: 'DGG'

sequence: false

#bert_config:
#  MicroRNA: "models/bert_mlm_MicroRNA/"
#  LncRNA: "models/bert_mlm_LncRNA/"
#  MessengerRNA: "models/bert_mlm_MessengerRNA/"
#  Protein: "models/bert_mlm_Protein/"
#  GO_term: "models/bert_mlm_GO_term/"
#  trainable: false

#max_length:
#  MicroRNA: 600
#  LncRNA: 1700
#  MessengerRNA: 1500
#  Protein: 1200
#  GO_term: 150

head_node_type: "Protein"
ntype_subset: "Protein"
filter_self_metapaths: true

use_reverse: true
add_parents: true
batch_size: 2048
feature: true
neighbor_loader: 'HGTLoader'
n_neighbors: 2048

attn_heads: 4
attn_activation: "LeakyReLU"
activation: "relu"
n_layers: 2
attn_dropout: 0.2
dropout: 0.0
layer_pooling: 'concat'

inductive: false

loss_type: "BCE_WITH_LOGITS"
max_epochs: 1000
sweep: true
lr: 0.001
weight_decay: 0.01
min_epochs: 60
#hours: 7
early_stopping: 15
