#dataset: "UniProtGOA_HUMAN"
deepgraphgo_data: '../DeepGraphGO/data'
root_path: "../Multiplex-Graph-Embedding/data/heteronetwork/HUMAN_gtex_uniprot_MirTarBase_LncBase_lncRNA2Target_STRING_mRNAprotein_network.pickle"

sequence: false

bert_config:
  MicroRNA: "models/bert_mlm_MicroRNA/"
  LncRNA: "models/bert_mlm_LncRNA/"
  MessengerRNA: "models/bert_mlm_MessengerRNA/"
  Protein: "models/bert_mlm_Protein/"
  GO_term: "models/bert_mlm_GO_term/"
  trainable: false

max_length:
  MicroRNA: 600
  LncRNA: 1700
  MessengerRNA: 1500
  Protein: 1200
  GO_term: 150

head_node_type: "Protein"
attn_activation: "LeakyReLU"
activation: "relu"

input_dropout: false
batch_size: 1024

loss_type: "BCE_WITH_LOGITS"
max_epochs: 300
sweep: true
lr: 0.01
min_epochs:
#hours: 3
early_stopping: 8
