dataset: "rna_ppi_go"
root_path: "data/gtex_rna_ppi_multiplex_network.pickle"
train_date: '2018-01-01'
sequence: false

bert_config:
  MicroRNA: "models/bert_mlm_MicroRNA/"
  LncRNA: "models/bert_mlm_LncRNA/"
  MessengerRNA: "models/bert_mlm_MessengerRNA/"
  Protein: "models/bert_mlm_Protein/"
  GO_term: "models/bert_mlm_GO_term/"
  trainable: false

max_length:
  MicroRNA: 600
  LncRNA: 1700
  MessengerRNA: 1500
  Protein: 1200
  GO_term: 150

head_node_type: "MessengerRNA"
layer_pooling: "last"

attn_activation: "LeakyReLU"
activation: "relu"

input_dropout: false
neg_sampling_ratio: 1000
batch_size: 15000

loss_type: "CONTRASTIVE_LOSS"
max_epochs: 300
sweep: true
lr: 0.01
hours: 1.5
