dataset: "rna_ppi_go"
root_path: "data/gtex_rna_ppi_multiplex_network.pickle"
train_date: '2018-01-01'

bert_config:
  MicroRNA: "models/bert_mlm_MicroRNA/"
  LncRNA: "models/bert_mlm_LncRNA/"
  MessengerRNA: "models/bert_mlm_MessengerRNA/"
  Protein: "models/bert_mlm_Protein/"
  GO_term: "models/bert_mlm_GO_term/"

max_length:
  MicroRNA: 600
  LncRNA: 1700
  MessengerRNA: 1500
  Protein: 1200
  GO_term: 150

head_node_type: "MessengerRNA"
layer_pooling: "last"

attn_activation: "LeakyReLU"
activation: "relu"

input_dropout: false
batch_size: 32768
max_epochs: 150
sweep: true
