dataset: "rna_ppi_go_mlm"
root_path: "data/gtex_rna_ppi_multiplex_network.pickle"

node_type: "MessengerRNA"
model: "armheb/DNA_bert_6"
load_path: "models/bert_mlm_MessengerRNA"
save_path: "models/bert_mlm_MessengerRNA"

num_hidden_layers: 2
num_attention_heads: 4
hidden_dropout_prob: 0.1
intermediate_size: 40
hidden_size: 128
num_labels: 128
gradient_checkpointing: true
position_embedding_type: none

max_length: 1500
batch_size: 100
lr: 0.00001
