dataset: "rna_ppi_go_mlm"
root_path: "data/gtex_rna_ppi_multiplex_network.pickle"

node_type: "MicroRNA"
model: "armheb/DNA_bert_3"
load_path: "models/bert_mlm_MicroRNA"
save_path: "models/bert_mlm_MicroRNA"

num_hidden_layers: 3
num_attention_heads: 4
hidden_dropout_prob: 0.1
intermediate_size: 128
hidden_size: 128
num_labels: 128
gradient_checkpointing: true

max_length: 155
batch_size: 400
lr: 0.00001
