dataset: "rna_ppi_go"
root_path: "data/gtex_rna_ppi_multiplex_network.pickle"

#load_path: "models/latte2go.ckpt"
save_path: "models/latte2go_2nd_e256.ckpt"

bert_config:
  MicroRNA: "models/bert_mlm_MicroRNA/"
  LncRNA: "models/bert_mlm_LncRNA/"
  MessengerRNA: "models/bert_mlm_MessengerRNA/"
  Protein: "models/bert_mlm_Protein/"
  GO_term: "models/bert_mlm_GO_term/"
  trainable: false
  minibatching: true

max_length:
  MicroRNA: 600
  LncRNA: 1700
  MessengerRNA: 1500
  Protein: 1200
  GO_term: 150

head_node_type: "MessengerRNA"
n_neighbors: 128
n_layers: 2
t_order: 2
embedding_dim: 256
layer_pooling: "last"

attn_heads: 4
attn_activation: "LeakyReLU"
attn_dropout: 0.0

batchnorm: true
layernorm: false
activation: "relu"
dropout: 0.2
input_dropout: false

batch_size: 16384
lr: 0.001
weight_decay: 0