dataset: "rna_ppi_go"
root_path: "data/gtex_rna_ppi_multiplex_network.pickle"

#load_path: "models/latte2go.ckpt"
save_path: "models/latte2go_2nd_e256.ckpt"

bert_config:
  MicroRNA: "models/bert_mlm_MicroRNA/"
  LncRNA: "models/bert_mlm_LncRNA/"
  MessengerRNA: "models/bert_mlm_MessengerRNA/"
  Protein: "models/bert_mlm_Protein/"
  GO_term: "models/bert_mlm_GO_term/"
  trainable: false
  minibatching: true

max_length:
  MicroRNA: 600
  LncRNA: 1700
  MessengerRNA: 1500
  Protein: 1200
  GO_term: 150

head_node_type: "MessengerRNA"
use_reverse: true
neighbor_loader: "NeighborLoader"
n_neighbors: 512
n_layers: 2
t_order: 2
embedding_dim: 128
layer_pooling: "last"

attn_heads: 2
attn_activation: "LeakyReLU"
attn_dropout: 0.10

batchnorm: false
layernorm: true
activation: "relu"
dropout: 0.2
neg_sampling_ratio: 600

loss_type: "CONTRASTIVE_LOSS"
batch_size: 2048
lr: 0.001
weight_decay: 0.01